version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      dockerfile: booksapp/Dockerfile
    restart: always
    ports:
      - "8021:8021"

    depends_on:
      - db
    volumes:
      - ./booksapp:/booksapp

volumes:
  postgres_data: