version: '3.8'

services:
  db:
    image:  "postgres:13"
    restart: always
    ports:
      - "9432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      dockerfile: booksapp/Dockerfile
    restart: always
    ports:
      - "8021:8021"

    depends_on:
      - db
    volumes:
      - ./booksapp:/booksapp
    env_file:
      - .env

volumes:
  postgres_data: