"""empty message

Revision ID: 4f8794f82da7
Revises: 8268c6d973f0
Create Date: 2024-09-20 06:16:30.580512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8794f82da7'
down_revision: Union[str, None] = '8268c6d973f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesstoken', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('accesstoken', 'id')
    # ### end Alembic commands ###
